# Generated by Django 3.2.4 on 2021-06-10 22:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import excursions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('slug', models.SlugField(help_text='Заполняется автоматически', max_length=255, unique=True, verbose_name='Слаг')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('extra', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Дополнительная информация')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала экскурсии')),
                ('max_people_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во человек')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость')),
                ('types', models.CharField(choices=[('individual', 'Индивидуальная'), ('group', 'Групповая')], default='individual', max_length=10, verbose_name='Тип')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Экскурсию',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Фото', max_length=100, verbose_name='Подпись фото')),
                ('image', models.ImageField(max_length=300, upload_to=excursions.models.excursions_photos_path, validators=[excursions.models.Photo.validate_image], verbose_name='Файл')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
